### ISSUE TITLE
Удалить временные файлы из репозитория

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2020-8-forum#11]
В репозиторий накоммитили `.DS_Store` — файлы со служебными данными macOS. Это мусор. Во-первых, на других ОС в нём смысла нет. Во-вторых, при изменении исходников в рабочем каталоге могут обновляться служебные данные в `.DS_Store` и этот файл будет светиться как изменённый в выводе `git status`, что тоже некрасиво.

Для удаления всех `.DS_Store` можно использовать следующие команды:
* на Windows:
  ```Batch
  for /r %f in (*.DS_Store) do git rm %f
  echo .DS_Store>>.gitignore

  git checkout -b remove-ds-store
  git add .gitignore
  git commit -m "Удалены .DS_Store (#11)"
  git push -u origin remove-ds-store
  ```
* на unix-like:
  ```Bash
  find -name .DS_Store -exec git rm {} \;
  echo .DS_Store>>.gitignore

  git checkout -b remove-ds-store
  git add .gitignore
  git commit -m "Удалены .DS_Store (#11)"
  git push -u origin remove-ds-store
  ```

Предложенные выше команды добавят также `.DS_Store` в `.gitignore` и отправят новую ветку на сервер. А дальше pull request и вливание.

P.S. А закомиченная папка `.idea` никому не мешает?

**Comment by azmetovdt** [comment]
Документация JetBrains [советует](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems) коммитить всё в папке `.idea`, кроме `workspace.xml`, `usage.statistics.xml`, `tasks.xml`  и `shelf`, содержащих пользовательские настройки. У нас несколько человек работает в JetBrains Webstorm.

**Comment by Mazdaywik** [comment]
@Ohstapit, спасибо, не знал. Некоторые добавляли в `.gitignore` всю папку `.idea`, поэтому я и спросил.

**Comment by VarenytsiaMykhailo** [comment]
Хммм, тоже не знал, что .idea можно оставлять)
