### ISSUE TITLE
Кнопка "Назад" на панели просмотра поста работает некорректно

### ISSUE THREAD

**Issue by azmetovdt** [bmstu-iu9/utp2020-8-forum#16]
**Поведение:** текущая реализация кнопки назад, использующая `history.back()` учитывает редиректы на страницу поста после отправления пользователем ответа на пост.
**Ожидаемое поведение:** по нажатию открывается список постов категории/всех постов, в зависимости от того, с какой страницы был открыт пост.

<img src="https://user-images.githubusercontent.com/27621223/87693598-da047080-c795-11ea-92e3-270496a0835a.gif" width="350">

**Comment by Mazdaywik** [comment]
Грамотный багрепорт! 👍
