### ISSUE TITLE
Рендеринг шаблонов основной страницы на основании информации с сервера с помощью express-handlebars

### ISSUE THREAD

**Issue by azmetovdt** [bmstu-iu9/utp2020-8-forum#2]
Требуется собирать шаблоны страниц на основании информации с сервера
### Список задач

- [x] Вынести минимальные и повторяющиеся элементы верстки в отдельные файлы в соответсвии с документацией модуля express-handlebars.
- [x]  В соответсвии с информацией, поступающей с сервера (массивов ответов на пост, массива постов и т.п.) генерировать необходимое количество элементов шаблона с соответсвующей передааваемой сервером информации.

**Comment by Mazdaywik** [comment]
К коммитам, решающим issues, лучше приписывать номера, например #2. Тогда они будут отображаться в заявках. А то заявка странно выглядит: открыта и закрыта без каких-либо пояснений. Либо добавлять соответствующие запросы на слияние в _Linked pull requests._
